# Generated by Django 6.0.5 on 2026-05-12 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='dpi',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefono',
        ),
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='ocupacion',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='procedencia',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='examenes/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.TextField()),
                ('historia_enfermedad', models.TextField()),
                ('medicos', models.TextField(blank=True, null=True)),
                ('quirurgicos', models.TextField(blank=True, null=True)),
                ('alergicos', models.TextField(blank=True, null=True)),
                ('traumaticos', models.TextField(blank=True, null=True)),
                ('g', models.CharField(blank=True, max_length=10, null=True)),
                ('p', models.CharField(blank=True, max_length=10, null=True)),
                ('c', models.CharField(blank=True, max_length=10, null=True)),
                ('a', models.CharField(blank=True, max_length=10, null=True)),
                ('hv', models.CharField(blank=True, max_length=10, null=True)),
                ('hm', models.CharField(blank=True, max_length=10, null=True)),
                ('menarquia', models.CharField(blank=True, max_length=50, null=True)),
                ('coitarquia', models.CharField(blank=True, max_length=50, null=True)),
                ('no_parejas', models.IntegerField(blank=True, null=True)),
                ('fur', models.DateField(blank=True, null=True)),
                ('ciclos_menstruales', models.CharField(blank=True, max_length=100, null=True)),
                ('planificacion_familiar', models.CharField(blank=True, max_length=150, null=True)),
                ('pa', models.CharField(blank=True, max_length=50, null=True)),
                ('fc', models.CharField(blank=True, max_length=50, null=True)),
                ('fr', models.CharField(blank=True, max_length=50, null=True)),
                ('temperatura', models.CharField(blank=True, max_length=50, null=True)),
                ('so2', models.CharField(blank=True, max_length=50, null=True)),
                ('peso', models.CharField(blank=True, max_length=50, null=True)),
                ('talla', models.CharField(blank=True, max_length=50, null=True)),
                ('imc', models.CharField(blank=True, max_length=50, null=True)),
                ('impresion_clinica', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('laboratorios', models.TextField(blank=True, null=True)),
                ('proxima_cita', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.paciente')),
            ],
        ),
    ]
