# Generated by Django 6.0.5 on 2026-05-13 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_paciente_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='sistema.historiaclinica')),
            ],
        ),
    ]
